version: '3'

services:
  twitter-scraper-mcp:
    build: .
    container_name: twitter-scraper-mcp
    environment:
      - HTTP_PROXY=http://host.docker.internal:7890
      - HTTPS_PROXY=http://host.docker.internal:7890
      - NODE_TLS_REJECT_UNAUTHORIZED=0
      # Twitter credentials from .env will be passed through
    env_file:
      - .env
    # No need to expose ports for stdio transport
    volumes:
      - .:/app
      - /app/node_modules
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
